export const ADD_TASK = 'ADD_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const FETCH_TASK = 'FETCH_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const GET_TASK_BY_ID = 'GET_TASK_BY_ID'
export const FETCH_TASK_FAIL = 'FETCH_TASK_FAIL'
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS'
